-- entity_id,
-- id,
-- original_title,
-- title,
-- original_language,
-- overview(ru),
-- plot(en),
-- year,
-- released,
-- runtime,
-- genre,
-- director,
-- writer,
-- actors,
-- country,
-- awards,
-- poster,
-- ratings[],
-- imdbRating,
-- imdbVotes,
-- imdbID,
-- production,

CREATE TABLE `film_info` (
  `entity_id` int(11) NOT NULL AUTO_INCREMENT,
  `id` int(11) NOT NULL,
  `original_title` text NOT NULL,
  `title` text NOT NULL,
  `original_language` text NOT NULL,
  `overview` text NOT NULL,
  `plot` text NOT NULL,
  `film_year` text NOT NULL,
  `released` text NOT NULL,
  `runtime` text NOT NULL,
  `genre` text NOT NULL,
  `director` text NOT NULL,
  `writer` text NOT NULL,
  `actors` text NOT NULL,
  `country` text NOT NULL,
  `awards` text NOT NULL,
  `poster` text NOT NULL,
  `ratings` text NOT NULL,
  `imdbRating` text NOT NULL,
  `imdbVotes` text NOT NULL,
  `imdbID` text NOT NULL,
  `production` text NOT NULL,
  PRIMARY KEY (`entity_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;
